### ISSUE TITLE
Feature request: Allow specifying crop region for image comparison

### ISSUE THREAD

**Issue by lukestein** [Slide-extractor-beta/slide-extractor#4]
I'm wondering if it would be possible to specify as optional command-line arguments pixel coordinates to be used for the difference comparison. The reason is that I have videos with not only slides, but a small overlay video of the speaker (Zoom recordings) in the corner, and live text captions overlayed at the bottom of the frame. I would love to be able to have these not contribute to the differencing calculation.

Amazing tool; thank you!

**Comment by FerociousCentaur** [comment]
Hi @lukestein , thanks for using my tool. I have added this feature. You can find its usage in the documentation and can install it from [here](https://pypi.org/project/slide-extractor/2.0.1/)

**Comment by lukestein** [comment]
> Hi @lukestein , thanks for using my tool. I have added this feature.

Thanks for this, and working great. If you're up for continued requests, it would be great to be able to make the preview and confirmation only show up with a command line flag.

I have a big folder of Zoom recordings and want to run them all like this, where the dimensions exclude the recording of the speaker so I only get the slides

```zsh
for file in *.mp4; do
    slide-extractor -p $file -s 3 -c "[[0,0],[720,1055]]"
done
```

Right now, this requires me to confirm with a keypress ("Please check the preview image for the area you want to be compared") for every file.
